### ISSUE TITLE
Warning: Component: isMounted is deprecated

### ISSUE THREAD

**Issue by ramusus** [CognizantStudio/react-loader#61]
I got this `Warning: Component: isMounted is deprecated. Instead, make sure to clean up subscriptions and pending requests in componentWillUnmount to prevent memory leaks.` using version 2.4.1 with React 15.5.4

**Comment by marcgarreau** [comment]
Just caught that @ramusus. Will address as soon as I have time later this evening. If you are interested in taking a stab at it before then, let me know.

**Comment by joelfsreis** [comment]
+1
