### ISSUE TITLE
Pass a component as an option

### ISSUE THREAD

**Issue by amanoharquickbase** [CognizantStudio/react-loader#64]
Is there a way to pass a component as a prop to the options prop for rendering that component instead of a spinner?

**Comment by amanoharquickbase** [comment]
@marcgarreau

**Comment by marcgarreau** [comment]
I'm afraid not, @amanoharquickbase. You can customize many attributes about the spinner, as you've probably seen [here](https://github.com/CognizantStudio/react-loader/blob/master/README.md#options) in the README or on the [spin.js demo page](http://spin.js.org/), but the library is coupled to spin.js for now.
