### ISSUE TITLE
React.StrictMode complains about using string ref

### ISSUE THREAD

**Issue by georgiosd** [CognizantStudio/react-loader#71]
Hi! 

I really like `React.StrictMode` but it generates a warning that you're still using a string ref vs createRef().

Any chance you can update this? :)

Thanks!

**Comment by nicholasserra** [comment]
Sounds sane, PRs welcome on this, thanks!

**Comment by mwilliamson-healx** [comment]
Would it be possible to make a release containing this change? So far as I can tell, the latest release 2.4.5 doesn't include this.

**Comment by nicholasserra** [comment]
@mwilliamson-healx 2.4.6 has now been published

**Comment by mwilliamson-healx** [comment]
Fantastic, thanks!
